
### Sign Up
POST {{ $dotenv VITE_API_URL }}/signUp HTTP/1.1
content-type: application/json

{
  "username": "mark+2@whywe.tech",
  "email": "mark+2@whywe.tech",
  "password": "Pass_w0rd"
}

### Sign In
POST {{ $dotenv VITE_API_URL }}/signIn HTTP/1.1
content-type: application/json

{
  "username": "mark+1@whywe.tech",
  "password": "Pass_w0rd"
}