
### Sign Up
POST {{ $dotenv VITE_API_URL }}/signUp HTTP/1.1
content-type: application/json

{
  "username": "mark+10@whywe.tech",
  "email": "mark+10@whywe.tech",
  "password": "Pass_w0rd"
}

### Sign In
POST {{ $dotenv VITE_API_URL }}/signIn HTTP/1.1
content-type: application/json

{
  "username": "mark+11@whywe.tech",
  "password": "Pass_w0rd"
}