### Sign Up
POST {{ $dotenv VITE_API_URL}}/signup HTTP/1.1
content-type: application/json

{
"username": "mark+test@whywe.tech",
"email": "mark+test@whywe.tech",
"password": "FastTrack#1"
}

### Sign In
POST {{dotenv VITE_API_URL}}/signin HTTP/1.1
content-type: application/json

{
  "username": "testuser",
  "password": "TestPassword1!"
}