
### Sign Up
POST {{ $dotenv VITE_API_URL }}/signUp HTTP/1.1
content-type: application/json

{
  "username": "mark+2@whywe.tech",
  "email": "mark+2@whywe.tech",
  "password": "Pass_w0rd"
}


### Sign In

# @name signin
POST {{ $dotenv VITE_API_URL }}/signIn HTTP/1.1
content-type: application/json

{
  "username": "mark+1@whywe.tech",
  "password": "Pass_w0rd"
}

### Save Log

@accessToken = {{ signin.response.body.AccessToken }}

POST {{ $dotenv VITE_API_URL }}/saveLog HTTP/1.1
content-type: application/json
Authorization: Bearer {{ signin.response.body.AccessToken }}

{
  "key": "test_key_2",
  "content": "Pass_w0rd"
}

### Get Log

@accessToken = {{ signin.response.body.AccessToken }}

GET {{ $dotenv VITE_API_URL }}/getLog HTTP/1.1
content-type: application/json
Authorization: Bearer {{ signin.response.body.AccessToken }}

?key=wrt

### GitHub app

GET {{ $dotenv VITE_GITHUB_ISSUER_URL }}


### GitHub auth

GET https://github.com/login/oauth/authorize