curl 'https://u4ceo7qshi.execute-api.us-east-1.amazonaws.com/prod/signup' `
-H 'accept: application/json, text/plain, */*' `
-H 'accept-language: en-US,en;q=0.9' `
-H 'content-type: application/json' `
-H 'origin: http://localhost:5173' `
-H 'priority: u=1, i' `
-H 'referer: http://localhost:5173/' `
-H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' `
-H 'sec-ch-ua-mobile: ?0' `
-H 'sec-ch-ua-platform: "Windows"' `
-H 'sec-fetch-dest: empty' `
-H 'sec-fetch-mode: cors' `
-H 'sec-fetch-site: cross-site' `
-H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0' `
--data-raw '{"username":"mark@bizkite.co","password":"Pass_w0rd","email":"mark@bizkite.co"}'